default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV.fetch('DB_NAME') { 'rails-on-docker-example' } %>
  username: <%= ENV.fetch('DB_USER') { 'root' } %>
  password: <%= ENV.fetch('DB_PASSWORD') { 'password' } %>
  host: <%= ENV.fetch('DB_HOST') { 'localhost' } %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default